codecov:
    notify:
        after_n_builds: 3
flags:
  composapi:
    carryforward: false
  composgh:
    carryforward: false
  integration:
    carryforward: false
ignore:
  - "ComposGHTests"  # ignore folders and all its contents